services:
  - type: web
    name: suzan-backend
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000